[General]
; EN: FrameWindow="Unreal Level Editor"
FrameWindow=""
; EN: Start="UnrealEd (Starting)"
Start=""
; EN: Exit="UnrealEd (Exiting)"
Exit=""
; EN: Run="UnrealEd (Running)"
Run=""
Product="UnrealEd"
Abbreviation="UEd"
